# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rl_agent_pb2 as rl__agent__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rl_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RLAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSystemStates = channel.unary_unary(
                '/RLAgent/SendSystemStates',
                request_serializer=rl__agent__pb2.SystemStatesRequest.SerializeToString,
                response_deserializer=rl__agent__pb2.SystemConfig.FromString,
                _registered_method=True)
        self.GetSystemConfig = channel.unary_unary(
                '/RLAgent/GetSystemConfig',
                request_serializer=rl__agent__pb2.ConfigRequest.SerializeToString,
                response_deserializer=rl__agent__pb2.SystemConfig.FromString,
                _registered_method=True)


class RLAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSystemStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSystemStates': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSystemStates,
                    request_deserializer=rl__agent__pb2.SystemStatesRequest.FromString,
                    response_serializer=rl__agent__pb2.SystemConfig.SerializeToString,
            ),
            'GetSystemConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemConfig,
                    request_deserializer=rl__agent__pb2.ConfigRequest.FromString,
                    response_serializer=rl__agent__pb2.SystemConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RLAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RLAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RLAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSystemStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RLAgent/SendSystemStates',
            rl__agent__pb2.SystemStatesRequest.SerializeToString,
            rl__agent__pb2.SystemConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RLAgent/GetSystemConfig',
            rl__agent__pb2.ConfigRequest.SerializeToString,
            rl__agent__pb2.SystemConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
