# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rl_agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rl_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erl_agent.proto\"\xeb\x01\n\x0bSystemState\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08ycsb_ops\x18\x02 \x01(\x05\x12\x12\n\nkmeans_ops\x18\x03 \x01(\x05\x12\x10\n\x08\x62\x61nk_ops\x18\x04 \x01(\x05\x12\x17\n\x0f\x63pu_utilization\x18\x05 \x01(\x01\x12\x1a\n\x12memory_utilization\x18\x06 \x01(\x01\x12\x11\n\ttotal_ops\x18\x07 \x01(\x05\x12\x12\n\ncore_count\x18\x08 \x01(\x05\x12\x1c\n\x14sim_threads_per_core\x18\t \x01(\x05\x12\x17\n\x0f\x65vict_threshold\x18\n \x01(\x05\"D\n\x13SystemStatesRequest\x12\x1c\n\x06states\x18\x01 \x03(\x0b\x32\x0c.SystemState\x12\x0f\n\x07node_id\x18\x02 \x01(\t\" \n\rConfigRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"`\n\x0cSystemConfig\x12\x17\n\x0f\x63ore_adjustment\x18\x01 \x01(\x05\x12\x19\n\x11thread_adjustment\x18\x02 \x01(\x05\x12\x1c\n\x14\x65vict_thr_adjustment\x18\x03 \x01(\x05\x32x\n\x07RLAgent\x12\x39\n\x10SendSystemStates\x12\x14.SystemStatesRequest\x1a\r.SystemConfig\"\x00\x12\x32\n\x0fGetSystemConfig\x12\x0e.ConfigRequest\x1a\r.SystemConfig\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rl_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMSTATE']._serialized_start=19
  _globals['_SYSTEMSTATE']._serialized_end=254
  _globals['_SYSTEMSTATESREQUEST']._serialized_start=256
  _globals['_SYSTEMSTATESREQUEST']._serialized_end=324
  _globals['_CONFIGREQUEST']._serialized_start=326
  _globals['_CONFIGREQUEST']._serialized_end=358
  _globals['_SYSTEMCONFIG']._serialized_start=360
  _globals['_SYSTEMCONFIG']._serialized_end=456
  _globals['_RLAGENT']._serialized_start=458
  _globals['_RLAGENT']._serialized_end=578
# @@protoc_insertion_point(module_scope)
